repos:
- repo: https://github.com/psf/black
  rev: 24.1.0
  hooks:
    - id: black
      files: ^resilient_importer/

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.282
  hooks:
    - id: ruff
      files: ^resilient_importer/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
    - id: mypy
      files: ^resilient_importer/
      additional_dependencies:
        - types-redis
